### ISSUE TITLE
Some early user feedback - nice work, keep going!

### ISSUE THREAD

**Issue by SansGuidon** [Xafloc/NoteFlow#1]
Hey, to follow up easily and share the feedback with this community, I'll cite the feedback I'd left you on Lobste.rs (https://lobste.rs/s/wk158y/localized_web_based_markdown_note_taking#c_giflqq)

- The readme mentions we can add note with a “add note” button but I don’t see any, only the CTRL+Enter works for me, it’s a bit confusing at first, maybe a mini help is worth adding in the UI.
- Editing existing notes is my favorite workflow as ADHD, especially from the home page, so I’d like an easier way to go back to any note and edit it, like without having to trigger a specific edit button. I’d like that if I click on a note, I enter edit mode automatically, without leaving the home page.
- I don’t see a way to remove a note? Let’s say I’ve added few accidental notes.
- The default example note should ideally show all possible uses, i.e how to add links to be archived. 
- I’ve edited a few notes with ‘+https://…’ but it does not seem to have any effect in several cases.
- I could trigger the archiving only by editing a note to make it contain only a link and nothing else, but then after hitting the save button the UI blocks for a while until I guess the archiving is made, it would be nice if it’s done in background without forcing the user to wait for dozens of seconds or more.
- After adding a link and going back to the main page, I had to refresh the page again so the link appears in the links “section” to the right of the page.
- I'm not sure how much links we can add per notes and if we can add many as I wasn't sure how to test this (didn't work for me) ? I'd like to paste lot of links and just have them archiving automatically without needing to type "+" as a prefix.
- If I add http://localhost:8000/ as a link, the app completely stop responding, I can’t even kill the process with CTRL+C so I’m forced to use a SIGKILL from another terminal
- It would be interesting to tell the user somewhere about which folder is served by the app, as you have said you can run the app from various folders, it would make sense to know in which context we are. Also maybe pick a different color based on the context so we can immediately tell which folder we are editing and avoid messing up. 

I can test further but I believe it should already help :-) 

Nice work, keep going!

**Comment by Xafloc** [comment]
Thanks for all the feedback and issue identification, I'll work through them! You must have a QA background haha!

**Comment by SansGuidon** [comment]
Ahah ! I forgot to mention about all the things that work well but I think you don't need a reminder for those :-) 
Maybe I have some QA skills, I'm not sure. What I know is, given the Murphy Law is a thing, when something wrong can happen, it will occur to me :-)

**Comment by Xafloc** [comment]
> What I know is, given the Murphy Law is a thing, when something wrong can happen, it will occur to me :-)

Works well for getting the bugs out of my code haha

**Comment by Xafloc** [comment]
## Pushed a few updates to Git, but not yet to any of the release systems:
- Added a "Save Note" button so that my readme wasn't lying :)
- Added a "delete" link to each note
- I believe I fixed the +site link adding issue on edit save not working occasionally, but haven't addressed your other issues yet. I may just restrict the "localhost" link to itself  until I figure out what's going on. I'll keep working on it.

Still going through the other feedback on edits, adding multiple sites, the ability to potentially archive in the background, etc.

**Comment by Xafloc** [comment]
I've addressed I believe all of these items, and would welcome a retest. Going to close this one, but welcome a new issue created with follow-up testing!
